#! /bin/bash

mpirun -np 8 python3 nfi1com.py h_uniform_k_2_j_0.dat 2 1 set13.dat
mpirun -np 8 python3 nfi1com.py h_uniform_k_2_j_0.dat 2 10 set13.dat
mpirun -np 8 python3 nfi1com.py h_uniform_k_2_j_0.dat 2 100 set13.dat

mpirun -np 8 python3 nfi1com.py g_uniform_k_2_j_0.dat 2 1 set13.dat
mpirun -np 8 python3 nfi1com.py g_uniform_k_2_j_0.dat 2 10 set13.dat
mpirun -np 8 python3 nfi1com.py g_uniform_k_2_j_0.dat 2 100 set13.dat

mpirun -np 8 python3 nfi1com.py z_uniform_k_2_j_0.dat 2 1 set13.dat
mpirun -np 8 python3 nfi1com.py z_uniform_k_2_j_0.dat 2 10 set13.dat
mpirun -np 8 python3 nfi1com.py z_uniform_k_2_j_0.dat 2 100 set13.dat

mpirun -np 8 python3 nfi1com.py r_uniform_k_2_j_0.dat 2 1 set13.dat
mpirun -np 8 python3 nfi1com.py r_uniform_k_2_j_0.dat 2 10 set13.dat
mpirun -np 8 python3 nfi1com.py r_uniform_k_2_j_0.dat 2 100 set13.dat

mpirun -np 8 python3 nfi1com.py h_uniform_k_2_j_1.dat 3 1 set14.dat
mpirun -np 8 python3 nfi1com.py h_uniform_k_2_j_1.dat 3 10 set14.dat
mpirun -np 8 python3 nfi1com.py h_uniform_k_2_j_1.dat 3 100 set14.dat

mpirun -np 8 python3 nfi1com.py g_uniform_k_2_j_1.dat 3 1 set14.dat
mpirun -np 8 python3 nfi1com.py g_uniform_k_2_j_1.dat 3 10 set14.dat
mpirun -np 8 python3 nfi1com.py g_uniform_k_2_j_1.dat 3 100 set14.dat

mpirun -np 8 python3 nfi1com.py z_uniform_k_2_j_1.dat 3 1 set14.dat
mpirun -np 8 python3 nfi1com.py z_uniform_k_2_j_1.dat 3 10 set14.dat
mpirun -np 8 python3 nfi1com.py z_uniform_k_2_j_1.dat 3 100 set14.dat

mpirun -np 8 python3 nfi1com.py r_uniform_k_2_j_1.dat 3 1 set14.dat
mpirun -np 8 python3 nfi1com.py r_uniform_k_2_j_1.dat 3 10 set14.dat
mpirun -np 8 python3 nfi1com.py r_uniform_k_2_j_1.dat 3 100 set14.dat

mpirun -np 8 python3 nfi1com.py h_uniform_k_2_j_2.dat 4 1 set15.dat
mpirun -np 8 python3 nfi1com.py h_uniform_k_2_j_2.dat 4 10 set15.dat
mpirun -np 8 python3 nfi1com.py h_uniform_k_2_j_2.dat 4 100 set15.dat

mpirun -np 8 python3 nfi1com.py g_uniform_k_2_j_2.dat 4 1 set15.dat
mpirun -np 8 python3 nfi1com.py g_uniform_k_2_j_2.dat 4 10 set15.dat
mpirun -np 8 python3 nfi1com.py g_uniform_k_2_j_2.dat 4 100 set15.dat

mpirun -np 8 python3 nfi1com.py z_uniform_k_2_j_2.dat 4 1 set15.dat
mpirun -np 8 python3 nfi1com.py z_uniform_k_2_j_2.dat 4 10 set15.dat
mpirun -np 8 python3 nfi1com.py z_uniform_k_2_j_2.dat 4 100 set15.dat

mpirun -np 8 python3 nfi1com.py r_uniform_k_2_j_2.dat 4 1 set15.dat
mpirun -np 8 python3 nfi1com.py r_uniform_k_2_j_2.dat 4 10 set15.dat
mpirun -np 8 python3 nfi1com.py r_uniform_k_2_j_2.dat 4 100 set15.dat

mpirun -np 8 python3 nfi1com.py h_uniform_k_2_j_3.dat 5 1 set16.dat
mpirun -np 8 python3 nfi1com.py h_uniform_k_2_j_3.dat 5 10 set16.dat
mpirun -np 8 python3 nfi1com.py h_uniform_k_2_j_3.dat 5 100 set16.dat

mpirun -np 8 python3 nfi1com.py g_uniform_k_2_j_3.dat 5 1 set16.dat
mpirun -np 8 python3 nfi1com.py g_uniform_k_2_j_3.dat 5 10 set16.dat
mpirun -np 8 python3 nfi1com.py g_uniform_k_2_j_3.dat 5 100 set16.dat

mpirun -np 8 python3 nfi1com.py z_uniform_k_2_j_3.dat 5 1 set16.dat
mpirun -np 8 python3 nfi1com.py z_uniform_k_2_j_3.dat 5 10 set16.dat
mpirun -np 8 python3 nfi1com.py z_uniform_k_2_j_3.dat 5 100 set16.dat

mpirun -np 8 python3 nfi1com.py r_uniform_k_2_j_3.dat 5 1 set16.dat
mpirun -np 8 python3 nfi1com.py r_uniform_k_2_j_3.dat 5 10 set16.dat
mpirun -np 8 python3 nfi1com.py r_uniform_k_2_j_3.dat 5 100 set16.dat



